/*
 * generated by Xtext
 */
package de.mathema.typesystem;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TypesystemRuntimeModule extends de.mathema.typesystem.AbstractTypesystemRuntimeModule {

}
