/*
* generated by Xtext
*/
package de.mathema.typesystem;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TypesystemStandaloneSetup extends TypesystemStandaloneSetupGenerated{

	public static void doSetup() {
		new TypesystemStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

