/*
 * generated by Xtext
 */
package de.mathema.typesystem.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TypesystemUiModule extends de.mathema.typesystem.ui.AbstractTypesystemUiModule {
	public TypesystemUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
