/*
 * generated by Xtext
 */
package de.mathema.typesystem.ui.contentassist

import de.mathema.typesystem.ui.contentassist.AbstractTypesystemProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TypesystemProposalProvider extends AbstractTypesystemProposalProvider {
}
