/*
* generated by Xtext
*/
package de.mathema.typesystem;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TypesystemUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.mathema.typesystem.ui.internal.TypesystemActivator.getInstance().getInjector("de.mathema.typesystem.Typesystem");
	}
	
}
